class FullError(Exception):
    pass


class OccupiedError(Exception):
    pass